CREATE TABLE IF NOT EXISTS users (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255),
  password VARCHAR(255),
  role VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS tickets (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  req_date VARCHAR(50),
  ticket_id VARCHAR(255),
  user_name VARCHAR(255),
  issue TEXT,
  engineer VARCHAR(255),
  status VARCHAR(100)
);
